version: '2'
services:
    rfb3-app:
        image: rfb3
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://rfb3-mysql:3306/rfb3?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    rfb3-mysql:
        extends:
            file: mysql.yml
            service: rfb3-mysql
